name: Build and Deploy Spring app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Spring Boot app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 11
          java-package: jdk
          distribution: 'temurin'
          check-latest: false
          server-id: github


      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application with Maven
        run: | 
          mvn clean
          mvn -B package --file pom.xml