name: Build and Deploy Spring app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Spring Boot app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v1
        with:
          java-version: 22
          java-package: jdk
          distribution: 'temurin'
          check-latest: false
          server-id: github


      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application with Maven
        run: | 
          mvn clean
          mvn -B package --file pom.xml
          

      - name: Build docker image
        uses: actions/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/CI-CD-pipeline:$(date +'%Y-%m-%d_%H-%M')
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: actions/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/CI-CD-pipeline:$(date +'%Y-%m-%d_%H-%M')

